### ISSUE TITLE
Rotate view in jsssm-viz

### ISSUE THREAD

**Issue by machinshin** [StoneCypher/jssm-viz#13]
It'd be cool  if there was a button to rotate the editor view & the graphviz view from L/R (Left/Right) to U/D (Up / Down) and vice versa.

**Comment by StoneCypher** [comment]
There is one.

![image](https://user-images.githubusercontent.com/77482/57270420-0c69f800-7040-11e9-916f-14f5bdea70e3.png)

Please use the unified issue tracker here: https://github.com/StoneCypher/fsl/issues

**Comment by StoneCypher** [comment]
in retrospect i should have confirmed i understood correctly then asked you to close the ticket.  sorry

**Comment by machinshin** [comment]
Nono, I want to be able to rotate from horizontal to vertical.

**Comment by StoneCypher** [comment]
ya that's what that button does.  click it

**Comment by StoneCypher** [comment]
oh wait do you mean the placement of the two panes?

like top bottom halves instead of right left halves?

**Comment by StoneCypher** [comment]
Will do this in the upcoming version of the editor
