### ISSUE TITLE
Viz not rendering.

### ISSUE THREAD

**Issue by MRIIOT** [StoneCypher/jssm-viz#26]
Here is an example, maybe not proper syntax, but does not render in entirety.

```
Init 'act-0' ~> Waiting;

[Waiting Cycle_Start Cycle_Finish] 'fault' -> Waiting;

Waiting 'act-1' => 
Cycle_Start 'act-2' => 
Cycle_Finish ~>
Waiting;
```

**Comment by StoneCypher** [comment]
You have two edges between `Cycle_Finish` and `Waiting`.  They're redundant.  This is disallowed by the language.

The core problem is that if you were at `Cycle_Finish` and instructed the language to change to `Waiting` it wouldn't know which edge to follow.  As the two edges can have differing consequences, the ambiguity is disallowed.

The machine throws an error.  It seems the editor isn't bubbling it up, though.

```
$ node
Welcome to Node.js v15.6.0.
Type ".help" for more information.
> let jssm = require('./dist/jssm.es5.cjs.js');
undefined
> const sm = jssm.sm;
undefined
> const machine = sm`
... Init 'act-0' ~> Waiting;
...
... [Waiting Cycle_Start Cycle_Finish] 'fault' -> Waiting;
...
... Waiting 'act-1' =>
... Cycle_Start 'act-2' =>
... Cycle_Finish ~>
... Waiting;
... `;
Uncaught Error: already has "Cycle_Finish" to "Waiting"
    at C:\Users\john\projects\jssm\dist\jssm.es5.cjs.js:1:250089
    at Array.map (<anonymous>)
    at new Machine (C:\Users\john\projects\jssm\dist\jssm.es5.cjs.js:1:249523)
    at sm (C:\Users\john\projects\jssm\dist\jssm.es5.cjs.js:1:257350)
```

Thanks for the notice.  I'll get this fixed

**Comment by StoneCypher** [comment]
This is probably StoneCypher/fsl#532

**Comment by StoneCypher** [comment]
![image](https://user-images.githubusercontent.com/77482/113501679-f8ed9300-94db-11eb-9e19-5a5c8150e455.png)

**Comment by StoneCypher** [comment]
The bug was that the editor was painting the error, then repainting the code, and the repaint of the code updates the status bar, which makes the error invisible

Doing them in the other order makes this visible again
